name: Create Images

on:
  workflow_dispatch:

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get-versions.outputs.versions }}
    steps:
      - name: Get Unity Versions
        id: get-versions
        run: |
          VERSIONS=$(head -n -1 versions.txt | tr '\n' ',')
          echo "::set-output name=versions::$VERSIONS"

  build-docker:
    needs: get-versions
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.lakes.house/

    strategy:
      matrix:
        platform: 
          - webgl
          - android
        version: ${{ fromJson(needs.get-versions.outputs.versions) }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: ./scripts/build-image.sh
        env:
          UNITY_VERSION: ${{ matrix.version }}
          UNITY_PLATFORM: ${{ matrix.platform }}
          IMAGE_NAME: ${{ env.DOCKER_REGISTRY }}unityci/editor
          GAMECI_VERSION: ${{ env.GAMECI_VERSION }}
          
      - name: Push Docker Image
        run: echo "TODO"