name: Create Images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    env:
      GAMECI_VERSION: 3
      PLATFORM: linux/amd64
      DOCKER_REGISTRY: docker.lakes.house

    strategy:
      matrix:
        platform: 
          - webgl
          - android
        version: 
          - 6000.0.35f1
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}  # usual credentials for bastion.local
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker Image
        run: |
            BASE_IMAGE=unityci/editor:ubuntu-${UNITY_VERSION}-${UNITY_PLATFORM}-${GAME_CI_VERSION}
            TAG=${{ env.DOCKER_REGISTRY }}/unityci/editor:ubuntu-${UNITY_VERSION}-${UNITY_PLATFORM}-runner
            docker build \
              --platform ${PLATFORM} \
              --build-arg GAME_CI_UNITY_EDITOR_IMAGE=${BASE_IMAGE} \
              -t ${TAG} \
              Dockerfiles/UnityEditor.Dockerfile
            
        env:
          UNITY_VERSION: ${{ matrix.version }}
          UNITY_PLATFORM: ${{ matrix.platform }}
    


